// ============================================================================
// DietWise - Regional Indian Vegetarian Food Database
// South Indian, Bengali, Gujarati, Punjabi, Rajasthani, and more
// ============================================================================

import type { FoodItem } from "./types";

export const REGIONAL_FOOD_DATABASE: FoodItem[] = [
  // =========================================================================
  // SOUTH INDIAN SPECIALTIES
  // =========================================================================
  {
    id: "si_rava_dosa",
    name: "Rava Dosa",
    nameHindi: "रवा दोसा",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 165, protein: 3, carbs: 22, fat: 7, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "si_pesarattu",
    name: "Pesarattu (Moong Dosa)",
    nameHindi: "पेसरट्टू",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 140, protein: 8, carbs: 18, fat: 3, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "si_appam",
    name: "Appam",
    nameHindi: "अप्पम",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 120, protein: 2, carbs: 22, fat: 2, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "si_puttu",
    name: "Puttu (Rice Cake)",
    nameHindi: "पुट्टु",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "cylinder",
    nutrition: { calories: 200, protein: 3, carbs: 38, fat: 4, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "si_avial",
    name: "Avial (Mixed Veg Curry)",
    nameHindi: "अवियल",
    category: "south_indian",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 130, protein: 3, carbs: 10, fat: 8, fiber: 3.5 },
    isVegetarian: true,
  },
  {
    id: "si_kootu",
    name: "Kootu (Lentil Veg Stew)",
    nameHindi: "कूटु",
    category: "south_indian",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 120, protein: 6, carbs: 14, fat: 4, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "si_pongal",
    name: "Ven Pongal",
    nameHindi: "वेन पोंगल",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 250, protein: 7, carbs: 35, fat: 8, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "si_medu_vada",
    name: "Medu Vada",
    nameHindi: "मेदु वड़ा",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 130, protein: 5, carbs: 13, fat: 6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "si_bisi_bele_bath",
    name: "Bisi Bele Bath",
    nameHindi: "बिसि बेले बाथ",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 280, protein: 8, carbs: 40, fat: 9, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "si_upma_vermicelli",
    name: "Semiya Upma (Vermicelli)",
    nameHindi: "सेमिया उपमा",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 220, protein: 5, carbs: 35, fat: 6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "si_tomato_rice",
    name: "Tomato Rice",
    nameHindi: "टमाटर चावल",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 240, protein: 4, carbs: 42, fat: 6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "si_tamarind_rice",
    name: "Puliyodarai (Tamarind Rice)",
    nameHindi: "इमली चावल",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 260, protein: 4, carbs: 44, fat: 7, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "si_coconut_rice",
    name: "Coconut Rice",
    nameHindi: "नारियल चावल",
    category: "south_indian",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 290, protein: 4, carbs: 40, fat: 12, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "si_ada_pradhaman",
    name: "Ada Pradhaman",
    nameHindi: "अड प्रधामन",
    category: "south_indian",
    servingSize: 150,
    servingUnit: "ml (1 bowl)",
    nutrition: { calories: 280, protein: 3, carbs: 40, fat: 12, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "si_ragi_mudde",
    name: "Ragi Mudde (Ragi Ball)",
    nameHindi: "रागी मुद्दे",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "ball (100g)",
    nutrition: { calories: 110, protein: 3, carbs: 22, fat: 1, fiber: 3.5 },
    isVegetarian: true,
  },
  {
    id: "si_neer_dosa",
    name: "Neer Dosa",
    nameHindi: "नीर दोसा",
    category: "south_indian",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 80, protein: 1.5, carbs: 16, fat: 1, fiber: 0.3 },
    isVegetarian: true,
  },
  {
    id: "si_payasam",
    name: "Payasam (Vermicelli Kheer)",
    nameHindi: "पायसम",
    category: "south_indian",
    servingSize: 150,
    servingUnit: "ml (1 bowl)",
    nutrition: { calories: 240, protein: 5, carbs: 35, fat: 8, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "si_thoran",
    name: "Thoran (Dry Veg Stir-fry)",
    nameHindi: "तोरन",
    category: "south_indian",
    servingSize: 100,
    servingUnit: "g (1 katori)",
    nutrition: { calories: 90, protein: 3, carbs: 6, fat: 6, fiber: 3.0 },
    isVegetarian: true,
  },

  // =========================================================================
  // BENGALI CUISINE
  // =========================================================================
  {
    id: "bn_luchi",
    name: "Luchi (Bengali Puri)",
    nameHindi: "लुची",
    category: "bengali",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 120, protein: 2, carbs: 14, fat: 6, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "bn_aloo_posto",
    name: "Aloo Posto (Potato Poppy Seed)",
    nameHindi: "आलू पोस्तो",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 180, protein: 3, carbs: 20, fat: 10, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "bn_shukto",
    name: "Shukto (Bitter Mixed Veg)",
    nameHindi: "शुक्तो",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 110, protein: 3, carbs: 10, fat: 6, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "bn_cholar_dal",
    name: "Cholar Dal (Bengal Gram)",
    nameHindi: "छोलार डाल",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 160, protein: 9, carbs: 22, fat: 4, fiber: 4.5 },
    isVegetarian: true,
  },
  {
    id: "bn_mochar_ghonto",
    name: "Mochar Ghonto (Banana Flower)",
    nameHindi: "मोचार घोंटो",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 130, protein: 3, carbs: 15, fat: 6, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "bn_mishti_doi",
    name: "Mishti Doi (Sweet Yogurt)",
    nameHindi: "मिष्टी दोई",
    category: "bengali",
    servingSize: 100,
    servingUnit: "g (1 cup)",
    nutrition: { calories: 135, protein: 4, carbs: 20, fat: 4, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "bn_sandesh",
    name: "Sandesh",
    nameHindi: "संदेश",
    category: "bengali",
    servingSize: 1,
    servingUnit: "piece (30g)",
    nutrition: { calories: 80, protein: 3, carbs: 12, fat: 2, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "bn_rasgulla",
    name: "Rasgulla",
    nameHindi: "रसगुल्ला",
    category: "bengali",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 125, protein: 2, carbs: 25, fat: 2, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "bn_begun_bhaja",
    name: "Begun Bhaja (Fried Brinjal)",
    nameHindi: "बेगुन भाजा",
    category: "bengali",
    servingSize: 3,
    servingUnit: "slices",
    nutrition: { calories: 100, protein: 1, carbs: 8, fat: 7, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "bn_phulkopir_dalna",
    name: "Phulkopir Dalna (Cauliflower Curry)",
    nameHindi: "फूलकोपिर डालना",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 120, protein: 3, carbs: 12, fat: 6, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "bn_doi_potol",
    name: "Doi Potol (Pointed Gourd in Yogurt)",
    nameHindi: "दोई पटोल",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 100, protein: 3, carbs: 8, fat: 6, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "bn_ghugni",
    name: "Ghugni (Dried Peas Curry)",
    nameHindi: "घुगनी",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 150, protein: 8, carbs: 20, fat: 4, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "bn_chhanar_dalna",
    name: "Chhanar Dalna (Paneer Curry)",
    nameHindi: "छेनार डालना",
    category: "bengali",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 200, protein: 10, carbs: 10, fat: 13, fiber: 1.5 },
    isVegetarian: true,
  },

  // =========================================================================
  // GUJARATI CUISINE
  // =========================================================================
  {
    id: "gj_undhiyu",
    name: "Undhiyu (Mixed Veg Casserole)",
    nameHindi: "ऊंधियू",
    category: "gujarati",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 200, protein: 5, carbs: 18, fat: 12, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "gj_handvo",
    name: "Handvo (Savory Cake)",
    nameHindi: "हांडवो",
    category: "gujarati",
    servingSize: 1,
    servingUnit: "piece (100g)",
    nutrition: { calories: 180, protein: 6, carbs: 25, fat: 5, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "gj_khandvi",
    name: "Khandvi",
    nameHindi: "खांडवी",
    category: "gujarati",
    servingSize: 5,
    servingUnit: "rolls",
    nutrition: { calories: 120, protein: 5, carbs: 16, fat: 3, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "gj_dal_dhokli",
    name: "Dal Dhokli",
    nameHindi: "दाल ढोकली",
    category: "gujarati",
    servingSize: 200,
    servingUnit: "ml (1 bowl)",
    nutrition: { calories: 260, protein: 10, carbs: 38, fat: 6, fiber: 3.5 },
    isVegetarian: true,
  },
  {
    id: "gj_sev_tameta",
    name: "Sev Tameta (Tomato Sev Curry)",
    nameHindi: "सेव टमेटा",
    category: "gujarati",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 170, protein: 3, carbs: 18, fat: 9, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "gj_gujarati_dal",
    name: "Gujarati Dal (Sweet-Sour)",
    nameHindi: "गुजराती दाल",
    category: "gujarati",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 140, protein: 7, carbs: 20, fat: 3, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "gj_patra",
    name: "Patra (Colocasia Leaf Rolls)",
    nameHindi: "पात्रा",
    category: "gujarati",
    servingSize: 3,
    servingUnit: "pieces",
    nutrition: { calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "gj_fafda",
    name: "Fafda",
    nameHindi: "फाफड़ा",
    category: "gujarati",
    servingSize: 3,
    servingUnit: "pieces (50g)",
    nutrition: { calories: 220, protein: 5, carbs: 22, fat: 12, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "gj_gathiya",
    name: "Gathiya",
    nameHindi: "गांठिया",
    category: "gujarati",
    servingSize: 30,
    servingUnit: "g",
    nutrition: { calories: 150, protein: 5, carbs: 15, fat: 8, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "gj_muthia",
    name: "Muthia (Steamed Dumplings)",
    nameHindi: "मुठिया",
    category: "gujarati",
    servingSize: 4,
    servingUnit: "pieces",
    nutrition: { calories: 150, protein: 4, carbs: 22, fat: 5, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "gj_shrikhand",
    name: "Shrikhand",
    nameHindi: "श्रीखंड",
    category: "gujarati",
    servingSize: 100,
    servingUnit: "g (1 katori)",
    nutrition: { calories: 200, protein: 6, carbs: 30, fat: 6, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "gj_basundi",
    name: "Basundi",
    nameHindi: "बासुंदी",
    category: "gujarati",
    servingSize: 100,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 185, protein: 5, carbs: 25, fat: 7, fiber: 0 },
    isVegetarian: true,
  },

  // =========================================================================
  // PUNJABI CUISINE
  // =========================================================================
  {
    id: "pj_sarson_ka_saag",
    name: "Sarson ka Saag",
    nameHindi: "सरसों का साग",
    category: "punjabi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 150, protein: 4, carbs: 10, fat: 10, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "pj_makki_roti",
    name: "Makki di Roti (Corn Roti)",
    nameHindi: "मक्की दी रोटी",
    category: "punjabi",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 130, protein: 3, carbs: 24, fat: 3, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "pj_paneer_tikka",
    name: "Paneer Tikka",
    nameHindi: "पनीर टिक्का",
    category: "punjabi",
    servingSize: 100,
    servingUnit: "g (4-5 pieces)",
    nutrition: { calories: 220, protein: 14, carbs: 5, fat: 16, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "pj_shahi_paneer",
    name: "Shahi Paneer",
    nameHindi: "शाही पनीर",
    category: "punjabi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 310, protein: 14, carbs: 10, fat: 24, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "pj_paneer_butter_masala",
    name: "Paneer Butter Masala",
    nameHindi: "पनीर बटर मसाला",
    category: "punjabi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 330, protein: 13, carbs: 12, fat: 26, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "pj_kadhi_pakora",
    name: "Kadhi Pakora",
    nameHindi: "कढ़ी पकोड़ा",
    category: "punjabi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 180, protein: 6, carbs: 15, fat: 10, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "pj_laccha_paratha",
    name: "Laccha Paratha",
    nameHindi: "लच्छा पराठा",
    category: "punjabi",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 230, protein: 4, carbs: 28, fat: 11, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "pj_gobhi_paratha",
    name: "Gobhi Paratha (Cauliflower)",
    nameHindi: "गोभी पराठा",
    category: "punjabi",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 210, protein: 4, carbs: 26, fat: 10, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "pj_paneer_paratha",
    name: "Paneer Paratha",
    nameHindi: "पनीर पराठा",
    category: "punjabi",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 260, protein: 9, carbs: 26, fat: 13, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "pj_lassi_sweet",
    name: "Sweet Lassi",
    nameHindi: "मीठी लस्सी",
    category: "punjabi",
    servingSize: 200,
    servingUnit: "ml (1 glass)",
    nutrition: { calories: 160, protein: 5, carbs: 24, fat: 4, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "pj_lassi_salt",
    name: "Salt Lassi",
    nameHindi: "नमकीन लस्सी",
    category: "punjabi",
    servingSize: 200,
    servingUnit: "ml (1 glass)",
    nutrition: { calories: 80, protein: 4, carbs: 8, fat: 3, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "pj_amritsari_kulcha",
    name: "Amritsari Kulcha",
    nameHindi: "अमृतसरी कुलचा",
    category: "punjabi",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 280, protein: 6, carbs: 38, fat: 10, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "pj_malai_kofta",
    name: "Malai Kofta",
    nameHindi: "मलाई कोफ्ता",
    category: "punjabi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 320, protein: 8, carbs: 16, fat: 25, fiber: 2.0 },
    isVegetarian: true,
  },

  // =========================================================================
  // RAJASTHANI CUISINE
  // =========================================================================
  {
    id: "rj_dal_baati_churma",
    name: "Dal Baati Churma",
    nameHindi: "दाल बाटी चूरमा",
    category: "rajasthani",
    servingSize: 1,
    servingUnit: "serving",
    nutrition: { calories: 450, protein: 12, carbs: 55, fat: 20, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "rj_gatte_ki_sabzi",
    name: "Gatte ki Sabzi",
    nameHindi: "गट्टे की सब्जी",
    category: "rajasthani",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 180, protein: 7, carbs: 18, fat: 9, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "rj_ker_sangri",
    name: "Ker Sangri",
    nameHindi: "केर सांगरी",
    category: "rajasthani",
    servingSize: 100,
    servingUnit: "g (1 katori)",
    nutrition: { calories: 120, protein: 3, carbs: 10, fat: 7, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "rj_papad_ki_sabzi",
    name: "Papad ki Sabzi",
    nameHindi: "पापड़ की सब्जी",
    category: "rajasthani",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 130, protein: 4, carbs: 12, fat: 7, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "rj_bajra_khichdi",
    name: "Bajra Khichdi (Rajasthani)",
    nameHindi: "बाजरा खिचड़ी",
    category: "rajasthani",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 250, protein: 8, carbs: 38, fat: 7, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "rj_mirchi_vada",
    name: "Mirchi Vada (Jodhpuri)",
    nameHindi: "मिर्ची वड़ा",
    category: "rajasthani",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 180, protein: 4, carbs: 18, fat: 10, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "rj_pyaaz_ki_kachori",
    name: "Pyaaz ki Kachori",
    nameHindi: "प्याज की कचौरी",
    category: "rajasthani",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 220, protein: 4, carbs: 22, fat: 12, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "rj_ghevar",
    name: "Ghevar",
    nameHindi: "घेवर",
    category: "rajasthani",
    servingSize: 1,
    servingUnit: "small piece",
    nutrition: { calories: 250, protein: 3, carbs: 35, fat: 10, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "rj_laal_maas_paneer",
    name: "Paneer Laal (Red Gravy)",
    nameHindi: "पनीर लाल",
    category: "rajasthani",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 260, protein: 12, carbs: 8, fat: 20, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "rj_mohan_thal",
    name: "Mohan Thal",
    nameHindi: "मोहन थाल",
    category: "rajasthani",
    servingSize: 1,
    servingUnit: "piece (30g)",
    nutrition: { calories: 130, protein: 3, carbs: 16, fat: 6, fiber: 0.5 },
    isVegetarian: true,
  },

  // =========================================================================
  // MORE COMMON INDIAN FOODS (filling gaps)
  // =========================================================================
  // Sweets & Desserts
  {
    id: "sweet_gulab_jamun",
    name: "Gulab Jamun",
    nameHindi: "गुलाब जामुन",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 150, protein: 2, carbs: 25, fat: 5, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "sweet_jalebi",
    name: "Jalebi",
    nameHindi: "जलेबी",
    category: "snack",
    servingSize: 2,
    servingUnit: "pieces",
    nutrition: { calories: 200, protein: 1, carbs: 35, fat: 7, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "sweet_ladoo_besan",
    name: "Besan Ladoo",
    nameHindi: "बेसन लड्डू",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece (30g)",
    nutrition: { calories: 140, protein: 3, carbs: 15, fat: 8, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "sweet_kheer",
    name: "Rice Kheer",
    nameHindi: "खीर",
    category: "dairy",
    servingSize: 150,
    servingUnit: "ml (1 bowl)",
    nutrition: { calories: 210, protein: 5, carbs: 32, fat: 7, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "sweet_halwa_suji",
    name: "Suji Halwa",
    nameHindi: "सूजी हलवा",
    category: "snack",
    servingSize: 100,
    servingUnit: "g (1 katori)",
    nutrition: { calories: 240, protein: 3, carbs: 32, fat: 11, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "sweet_gajar_halwa",
    name: "Gajar ka Halwa",
    nameHindi: "गाजर का हलवा",
    category: "snack",
    servingSize: 100,
    servingUnit: "g (1 katori)",
    nutrition: { calories: 200, protein: 3, carbs: 28, fat: 9, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "sweet_barfi",
    name: "Kaju Barfi",
    nameHindi: "काजू बर्फी",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece (25g)",
    nutrition: { calories: 120, protein: 2, carbs: 15, fat: 6, fiber: 0.3 },
    isVegetarian: true,
  },

  // Additional Sabzis
  {
    id: "sabzi_paneer_do_pyaza",
    name: "Paneer Do Pyaza",
    nameHindi: "पनीर दो प्याजा",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 250, protein: 12, carbs: 10, fat: 18, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "sabzi_matar_paneer",
    name: "Matar Paneer",
    nameHindi: "मटर पनीर",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 240, protein: 12, carbs: 12, fat: 16, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "sabzi_dum_aloo",
    name: "Dum Aloo",
    nameHindi: "दम आलू",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 200, protein: 4, carbs: 22, fat: 10, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "sabzi_chana_masala",
    name: "Chana Masala",
    nameHindi: "चना मसाला",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 175, protein: 9, carbs: 24, fat: 5, fiber: 5.5 },
    isVegetarian: true,
  },
  {
    id: "sabzi_navratan_korma",
    name: "Navratan Korma",
    nameHindi: "नवरत्न कोरमा",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 220, protein: 5, carbs: 16, fat: 15, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "sabzi_veg_kolhapuri",
    name: "Veg Kolhapuri",
    nameHindi: "वेज कोल्हापुरी",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 180, protein: 5, carbs: 14, fat: 12, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "sabzi_aloo_jeera",
    name: "Aloo Jeera",
    nameHindi: "आलू जीरा",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 150, protein: 2, carbs: 20, fat: 7, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "sabzi_bhindi_masala",
    name: "Bhindi Masala (Dry)",
    nameHindi: "भिंडी मसाला",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 100, protein: 3, carbs: 8, fat: 6, fiber: 3.5 },
    isVegetarian: true,
  },
  {
    id: "sabzi_kadai_paneer",
    name: "Kadai Paneer",
    nameHindi: "कड़ाही पनीर",
    category: "sabzi",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 280, protein: 14, carbs: 8, fat: 22, fiber: 2.0 },
    isVegetarian: true,
  },

  // Additional Dals
  {
    id: "dal_panchmel",
    name: "Panchmel Dal (5 Lentil Mix)",
    nameHindi: "पंचमेल दाल",
    category: "dal",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 145, protein: 9, carbs: 19, fat: 3, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "dal_tadka",
    name: "Dal Tadka",
    nameHindi: "दाल तड़का",
    category: "dal",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 135, protein: 8, carbs: 17, fat: 4, fiber: 3.5 },
    isVegetarian: true,
  },
  {
    id: "dal_palak",
    name: "Palak Dal",
    nameHindi: "पालक दाल",
    category: "dal",
    servingSize: 150,
    servingUnit: "ml (1 katori)",
    nutrition: { calories: 125, protein: 8, carbs: 15, fat: 3, fiber: 4.0 },
    isVegetarian: true,
  },

  // Additional Breads
  {
    id: "bread_kulcha",
    name: "Kulcha",
    nameHindi: "कुलचा",
    category: "bread",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 250, protein: 6, carbs: 40, fat: 6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "bread_bhatura",
    name: "Bhatura",
    nameHindi: "भटूरा",
    category: "bread",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 300, protein: 5, carbs: 35, fat: 15, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "bread_tandoori_roti",
    name: "Tandoori Roti",
    nameHindi: "तंदूरी रोटी",
    category: "bread",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 100, protein: 3, carbs: 18, fat: 1.5, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "bread_roomali_roti",
    name: "Roomali Roti",
    nameHindi: "रुमाली रोटी",
    category: "bread",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 120, protein: 3, carbs: 22, fat: 2, fiber: 1.0 },
    isVegetarian: true,
  },

  // Additional Rice
  {
    id: "rice_vangi_bath",
    name: "Vangi Bath (Brinjal Rice)",
    nameHindi: "वांगी बाथ",
    category: "rice",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 260, protein: 5, carbs: 40, fat: 8, fiber: 2.0 },
    isVegetarian: true,
  },

  // Additional Fruits
  {
    id: "fruit_kiwi",
    name: "Kiwi",
    nameHindi: "कीवी",
    category: "fruit",
    servingSize: 70,
    servingUnit: "g (1 medium)",
    nutrition: { calories: 42, protein: 0.8, carbs: 10, fat: 0.3, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "fruit_strawberry",
    name: "Strawberry",
    nameHindi: "स्ट्रॉबेरी",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g (6-8 pieces)",
    nutrition: { calories: 32, protein: 0.7, carbs: 7.5, fat: 0.3, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "fruit_chikoo",
    name: "Chikoo (Sapota)",
    nameHindi: "चीकू",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g (1 medium)",
    nutrition: { calories: 83, protein: 0.4, carbs: 20, fat: 1, fiber: 5.0 },
    isVegetarian: true,
  },
  {
    id: "fruit_custard_apple",
    name: "Custard Apple (Sitaphal)",
    nameHindi: "सीताफल",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g (flesh)",
    nutrition: { calories: 94, protein: 1.6, carbs: 23, fat: 0.3, fiber: 4.4 },
    isVegetarian: true,
  },
  {
    id: "fruit_jackfruit",
    name: "Jackfruit (Ripe)",
    nameHindi: "कटहल (पका)",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g",
    nutrition: { calories: 95, protein: 1.7, carbs: 23, fat: 0.6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "fruit_litchi",
    name: "Litchi",
    nameHindi: "लीची",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g (8-10 pieces)",
    nutrition: { calories: 66, protein: 0.8, carbs: 16, fat: 0.4, fiber: 1.3 },
    isVegetarian: true,
  },
  {
    id: "fruit_jamun",
    name: "Jamun (Indian Blackberry)",
    nameHindi: "जामुन",
    category: "fruit",
    servingSize: 100,
    servingUnit: "g",
    nutrition: { calories: 60, protein: 0.7, carbs: 14, fat: 0.2, fiber: 0.9 },
    isVegetarian: true,
  },
  {
    id: "fruit_amla",
    name: "Amla (Indian Gooseberry)",
    nameHindi: "आंवला",
    category: "fruit",
    servingSize: 50,
    servingUnit: "g (2 pieces)",
    nutrition: { calories: 23, protein: 0.4, carbs: 5.5, fat: 0.1, fiber: 2.2 },
    isVegetarian: true,
  },

  // Additional Breakfast
  {
    id: "breakfast_sabudana_khichdi",
    name: "Sabudana Khichdi",
    nameHindi: "साबूदाना खिचड़ी",
    category: "breakfast",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 280, protein: 4, carbs: 42, fat: 10, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "breakfast_rava_idli",
    name: "Rava Idli",
    nameHindi: "रवा इडली",
    category: "breakfast",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 70, protein: 2, carbs: 12, fat: 1, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "breakfast_muesli",
    name: "Muesli with Milk",
    nameHindi: "मूसली",
    category: "breakfast",
    servingSize: 50,
    servingUnit: "g with 150ml milk",
    nutrition: { calories: 270, protein: 9, carbs: 38, fat: 8, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "breakfast_cornflakes",
    name: "Corn Flakes with Milk",
    nameHindi: "कॉर्न फ्लेक्स",
    category: "breakfast",
    servingSize: 30,
    servingUnit: "g with 150ml milk",
    nutrition: { calories: 190, protein: 6, carbs: 30, fat: 4, fiber: 1.0 },
    isVegetarian: true,
  },

  // Additional Drinks
  {
    id: "drink_masala_chai",
    name: "Masala Chai (with milk, no sugar)",
    nameHindi: "मसाला चाय",
    category: "drink",
    servingSize: 150,
    servingUnit: "ml (1 cup)",
    nutrition: { calories: 50, protein: 2, carbs: 5, fat: 2, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "drink_chai_sugar",
    name: "Chai (with milk & sugar)",
    nameHindi: "चाय",
    category: "drink",
    servingSize: 150,
    servingUnit: "ml (1 cup)",
    nutrition: { calories: 80, protein: 2, carbs: 12, fat: 2, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "drink_coffee_milk",
    name: "Filter Coffee (with milk)",
    nameHindi: "फिल्टर कॉफी",
    category: "drink",
    servingSize: 150,
    servingUnit: "ml (1 cup)",
    nutrition: { calories: 70, protein: 2, carbs: 8, fat: 3, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "drink_black_coffee",
    name: "Black Coffee",
    nameHindi: "ब्लैक कॉफी",
    category: "drink",
    servingSize: 200,
    servingUnit: "ml (1 cup)",
    nutrition: { calories: 5, protein: 0.3, carbs: 0.5, fat: 0, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "drink_sugarcane_juice",
    name: "Sugarcane Juice",
    nameHindi: "गन्ने का रस",
    category: "drink",
    servingSize: 200,
    servingUnit: "ml (1 glass)",
    nutrition: { calories: 140, protein: 0.3, carbs: 35, fat: 0, fiber: 0 },
    isVegetarian: true,
  },
  {
    id: "drink_aam_panna",
    name: "Aam Panna (Raw Mango Drink)",
    nameHindi: "आम पन्ना",
    category: "drink",
    servingSize: 200,
    servingUnit: "ml (1 glass)",
    nutrition: { calories: 70, protein: 0.2, carbs: 17, fat: 0.1, fiber: 0.5 },
    isVegetarian: true,
  },
  {
    id: "drink_jaljeera",
    name: "Jaljeera",
    nameHindi: "जलजीरा",
    category: "drink",
    servingSize: 200,
    servingUnit: "ml (1 glass)",
    nutrition: { calories: 20, protein: 0.3, carbs: 4, fat: 0.2, fiber: 0.3 },
    isVegetarian: true,
  },

  // Additional Snacks
  {
    id: "snack_samosa",
    name: "Samosa (Aloo)",
    nameHindi: "समोसा",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 220, protein: 4, carbs: 24, fat: 12, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_kachori",
    name: "Kachori (Dal)",
    nameHindi: "कचौरी",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 200, protein: 4, carbs: 20, fat: 11, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_pakora",
    name: "Pakora / Bhajiya (mixed veg)",
    nameHindi: "पकोड़ा / भजिया",
    category: "snack",
    servingSize: 4,
    servingUnit: "pieces",
    nutrition: { calories: 180, protein: 4, carbs: 16, fat: 10, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_aloo_tikki",
    name: "Aloo Tikki",
    nameHindi: "आलू टिक्की",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 160, protein: 3, carbs: 20, fat: 7, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_bread_pakora",
    name: "Bread Pakora",
    nameHindi: "ब्रेड पकोड़ा",
    category: "snack",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 160, protein: 3, carbs: 18, fat: 8, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "snack_pani_puri",
    name: "Pani Puri / Gol Gappa",
    nameHindi: "पानी पूरी / गोल गप्पा",
    category: "snack",
    servingSize: 6,
    servingUnit: "pieces",
    nutrition: { calories: 150, protein: 3, carbs: 25, fat: 4, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_sev_puri",
    name: "Sev Puri",
    nameHindi: "सेव पूरी",
    category: "snack",
    servingSize: 4,
    servingUnit: "pieces",
    nutrition: { calories: 160, protein: 3, carbs: 22, fat: 6, fiber: 1.5 },
    isVegetarian: true,
  },
  {
    id: "snack_bhel_puri",
    name: "Bhel Puri",
    nameHindi: "भेल पूरी",
    category: "snack",
    servingSize: 1,
    servingUnit: "plate",
    nutrition: { calories: 150, protein: 3, carbs: 24, fat: 4, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "snack_dahi_vada",
    name: "Dahi Vada",
    nameHindi: "दही वड़ा",
    category: "snack",
    servingSize: 2,
    servingUnit: "pieces",
    nutrition: { calories: 180, protein: 6, carbs: 22, fat: 7, fiber: 2.0 },
    isVegetarian: true,
  },

  // Additional Other
  {
    id: "other_roti_wrap_veg",
    name: "Veg Roti Wrap / Frankie",
    nameHindi: "वेज रोटी रैप",
    category: "other",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 250, protein: 6, carbs: 30, fat: 11, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "other_veg_sandwich",
    name: "Veg Sandwich (brown bread)",
    nameHindi: "वेज सैंडविच",
    category: "other",
    servingSize: 1,
    servingUnit: "sandwich",
    nutrition: { calories: 200, protein: 5, carbs: 28, fat: 7, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "other_veg_momos",
    name: "Veg Momos (Steamed)",
    nameHindi: "वेज मोमोज",
    category: "other",
    servingSize: 6,
    servingUnit: "pieces",
    nutrition: { calories: 200, protein: 5, carbs: 28, fat: 6, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "other_veg_fried_rice",
    name: "Veg Fried Rice",
    nameHindi: "वेज फ्राइड राइस",
    category: "other",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 280, protein: 5, carbs: 40, fat: 10, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "other_veg_noodles",
    name: "Veg Hakka Noodles",
    nameHindi: "वेज हक्का नूडल्स",
    category: "other",
    servingSize: 200,
    servingUnit: "g (1 plate)",
    nutrition: { calories: 300, protein: 5, carbs: 42, fat: 11, fiber: 2.0 },
    isVegetarian: true,
  },
  {
    id: "other_pav_bhaji",
    name: "Pav Bhaji",
    nameHindi: "पाव भाजी",
    category: "other",
    servingSize: 1,
    servingUnit: "plate (2 pav + bhaji)",
    nutrition: { calories: 400, protein: 8, carbs: 50, fat: 18, fiber: 4.0 },
    isVegetarian: true,
  },
  {
    id: "other_misal_pav",
    name: "Misal Pav",
    nameHindi: "मिसल पाव",
    category: "other",
    servingSize: 1,
    servingUnit: "plate",
    nutrition: { calories: 350, protein: 12, carbs: 42, fat: 14, fiber: 5.0 },
    isVegetarian: true,
  },
  {
    id: "other_vada_pav",
    name: "Vada Pav",
    nameHindi: "वड़ा पाव",
    category: "other",
    servingSize: 1,
    servingUnit: "piece",
    nutrition: { calories: 290, protein: 5, carbs: 35, fat: 13, fiber: 2.5 },
    isVegetarian: true,
  },
  {
    id: "other_chole_bhature",
    name: "Chole Bhature",
    nameHindi: "छोले भटूरे",
    category: "other",
    servingSize: 1,
    servingUnit: "plate (2 bhature + chole)",
    nutrition: { calories: 520, protein: 14, carbs: 56, fat: 26, fiber: 5.0 },
    isVegetarian: true,
  },
  {
    id: "other_aloo_chaat",
    name: "Aloo Chaat",
    nameHindi: "आलू चाट",
    category: "other",
    servingSize: 1,
    servingUnit: "plate",
    nutrition: { calories: 200, protein: 3, carbs: 28, fat: 8, fiber: 3.0 },
    isVegetarian: true,
  },
  {
    id: "other_egg_substitute_tofu_scramble",
    name: "Tofu Scramble (Egg alternative)",
    nameHindi: "टोफू स्क्रैम्बल",
    category: "other",
    servingSize: 100,
    servingUnit: "g",
    nutrition: { calories: 130, protein: 12, carbs: 3, fat: 8, fiber: 1.0 },
    isVegetarian: true,
  },
  {
    id: "other_multigrain_atta",
    name: "Multigrain Roti",
    nameHindi: "मल्टीग्रेन रोटी",
    category: "bread",
    servingSize: 1,
    servingUnit: "medium",
    nutrition: { calories: 85, protein: 3, carbs: 16, fat: 1, fiber: 2.5 },
    isVegetarian: true,
  },
];
